from __future__ import annotations

from datetime import datetime
from typing import Protocol, Sequence

from app.domain.entities import (
    AuditEvent,
    CalculationOutcome,
    Delegation,
    HistoryFilter,
    Order,
    OrderStudy,
    PanelDefinition,
    Patient,
    ResultChange,
    ResultVersion,
    StudyDefinition,
    Value,
)


class PatientRepository(Protocol):
    def get_by_id(self, id_paciente: int) -> Patient | None: ...
    def get_by_ci(self, ci: str) -> Patient | None: ...
    def search(self, query: str, limit: int = 50) -> Sequence[Patient]: ...
    def add(self, patient: Patient) -> Patient: ...
    def save(self, patient: Patient) -> Patient: ...


class UserRepository(Protocol):
    def exists_active_bioquimico(self, id_usuario: int) -> bool: ...
    def exists_active_admin(self, id_usuario: int) -> bool: ...


class StudyRepository(Protocol):
    def get_active(self, id_estudio: int) -> StudyDefinition | None: ...
    def get_version(self, id_estudio_version: int) -> StudyDefinition | None: ...
    def list_active(self) -> Sequence[StudyDefinition]: ...


class PanelRepository(Protocol):
    def list_active(self) -> Sequence[PanelDefinition]: ...
    def get_active(self, id_panel: int) -> PanelDefinition | None: ...
    def list_studies(self, id_panel: int) -> Sequence[StudyDefinition]: ...


class OrderRepository(Protocol):
    def next_folio(self) -> str: ...
    def get_by_id(self, id_orden: int) -> Order | None: ...
    def get_order_for_study(self, id_orden_estudio: int) -> tuple[Order, OrderStudy] | None: ...
    def add(self, order: Order) -> Order: ...
    def save(self, order: Order) -> Order: ...
    def list_official(self, filters: HistoryFilter) -> Sequence[Order]: ...
    def list_trash(self, id_usuario: int) -> Sequence[Order]: ...
    def list_by_author(self, id_usuario: int) -> Sequence[Order]: ...
    def get_trash(self, id_orden: int) -> Order | None: ...


class ResultRepository(Protocol):
    def get_draft(self, id_orden_estudio: int) -> ResultVersion | None: ...
    def get_latest(self, id_orden_estudio: int) -> ResultVersion | None: ...
    def list_versions(self, id_orden_estudio: int) -> Sequence[ResultVersion]: ...
    def save_draft(self, result: ResultVersion) -> ResultVersion: ...
    def add_correction(self, result: ResultVersion, changes: Sequence[ResultChange]) -> ResultVersion: ...
    def save(self, result: ResultVersion) -> ResultVersion: ...
    def save_changes(self, changes: Sequence[ResultChange], id_resultado_version: int) -> None: ...
    def latest_official_order_results(self, id_orden: int) -> Sequence[ResultVersion]: ...
    def list_for_order_study(self, id_orden_estudio: int) -> Sequence[ResultVersion]: ...


class DelegationRepository(Protocol):
    def get_by_id(self, id_delegacion: int) -> Delegation | None: ...
    def get_active_for_order(self, id_orden: int) -> Delegation | None: ...
    def list_for_collaborator(self, id_usuario: int) -> Sequence[Delegation]: ...
    def list_for_order(self, id_orden: int) -> Sequence[Delegation]: ...
    def add(self, delegation: Delegation) -> Delegation: ...
    def save(self, delegation: Delegation) -> Delegation: ...


class AuditRepository(Protocol):
    def add(self, event: AuditEvent) -> None: ...
    def list_changes(self, id_orden: int) -> Sequence[ResultChange]: ...
    def list_recent(self, limit: int = 200) -> Sequence[AuditEvent]: ...
    def list_for_order(self, id_orden: int, limit: int = 200) -> Sequence[AuditEvent]: ...
    def add_security_event(
        self,
        id_usuario: int | None,
        evento: str,
        ip_origen: str | None = None,
        user_agent: str | None = None,
        detalles: dict[str, object] | None = None,
    ) -> None: ...


class CalculationPort(Protocol):
    def calculate(self, strategy: str, inputs: dict[str, Value]) -> CalculationOutcome: ...


class PdfPort(Protocol):
    def render_official(self, order: Order, results: Sequence[ResultVersion]) -> bytes: ...


class UnitOfWork(Protocol):
    patients: PatientRepository
    users: UserRepository
    studies: StudyRepository
    panels: PanelRepository
    orders: OrderRepository
    results: ResultRepository
    delegations: DelegationRepository
    audits: AuditRepository

    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class Clock(Protocol):
    def now(self) -> datetime: ...